const assetDeletes = [
	{
		DeleteNo: 1,
		AssetCode: 'A001',
		AssetName: '데스크탑 컴퓨터',
		DeleteDate: '2024-09-01',
		DeleteReason: '노후화',
		DeleteMethod: '재활용',
		DeleteLocation: '서울 본사',
		DeleteBy: '이창현',
	},
	{
		DeleteNo: 2,
		AssetCode: 'A002',
		AssetName: '프린터',
		DeleteDate: '2024-09-02',
		DeleteReason: '고장',
		DeleteMethod: '폐기',
		DeleteLocation: '부산 지사',
		DeleteBy: '김영희',
	},
	{
		DeleteNo: 3,
		AssetCode: 'A003',
		AssetName: '서버 장비',
		DeleteDate: '2024-09-03',
		DeleteReason: '성능 저하',
		DeleteMethod: '교체',
		DeleteLocation: '대전 지사',
		DeleteBy: '박철수',
	},
	{
		DeleteNo: 4,
		AssetCode: 'A004',
		AssetName: '노트북',
		DeleteDate: '2024-09-04',
		DeleteReason: '업그레이드 필요',
		DeleteMethod: '교체',
		DeleteLocation: '서울 본사',
		DeleteBy: '최민수',
	},
	{
		DeleteNo: 5,
		AssetCode: 'A005',
		AssetName: '프로젝터',
		DeleteDate: '2024-09-05',
		DeleteReason: '고장',
		DeleteMethod: '폐기',
		DeleteLocation: '부산 지사',
		DeleteBy: '정미래',
	},
	{
		DeleteNo: 6,
		AssetCode: 'A006',
		AssetName: '데이터베이스 서버',
		DeleteDate: '2024-09-06',
		DeleteReason: '시스템 업데이트',
		DeleteMethod: '업그레이드',
		DeleteLocation: '대구 지사',
		DeleteBy: '이철수',
	},
	{
		DeleteNo: 7,
		AssetCode: 'A007',
		AssetName: '네트워크 스위치',
		DeleteDate: '2024-09-07',
		DeleteReason: '성능 저하',
		DeleteMethod: '교체',
		DeleteLocation: '인천 지사',
		DeleteBy: '김지은',
	},
	{
		DeleteNo: 8,
		AssetCode: 'A008',
		AssetName: '프로젝터 스크린',
		DeleteDate: '2024-09-08',
		DeleteReason: '파손',
		DeleteMethod: '폐기',
		DeleteLocation: '서울 본사',
		DeleteBy: '윤주원',
	},
	{
		DeleteNo: 9,
		AssetCode: 'A009',
		AssetName: '데이터 백업 장비',
		DeleteDate: '2024-09-09',
		DeleteReason: '노후화',
		DeleteMethod: '재활용',
		DeleteLocation: '부산 지사',
		DeleteBy: '한가람',
	},
	{
		DeleteNo: 10,
		AssetCode: 'A010',
		AssetName: '회의실 TV',
		DeleteDate: '2024-09-10',
		DeleteReason: '화면 이상',
		DeleteMethod: '교체',
		DeleteLocation: '서울 본사',
		DeleteBy: '오민석',
	},
];

export { assetDeletes };
