const assetUpdates = [
	{
		UpdateNo: 1,
		AssetCode: 'ASSET001',
		AssetName: '프린터',
		UpdateDate: '2024-09-06',
		UpdateBy: '이창현',
		AssetClassification: 'SOFTWARE',
		UpdateReason: '펌웨어 업데이트',
	},
	{
		UpdateNo: 2,
		AssetCode: 'ASSET002',
		AssetName: '컴퓨터',
		UpdateDate: '2024-09-07',
		UpdateBy: '김영희',
		AssetClassification: 'SOFTWARE',
		UpdateReason: '하드웨어 교체',
	},
	{
		UpdateNo: 3,
		AssetCode: 'ASSET003',
		AssetName: '모니터',
		UpdateDate: '2024-09-08',
		UpdateBy: '박철수',
		AssetClassification: 'SOFTWARE',
		UpdateReason: '해상도 문제 수정',
	},
	{
		UpdateNo: 4,
		AssetCode: 'ASSET004',
		AssetName: '키보드',
		UpdateDate: '2024-09-09',
		UpdateBy: '최민수',
		AssetClassification: 'SOFTWARE',
		UpdateReason: '불량 키 교체',
	},
	{
		UpdateNo: 5,
		AssetCode: 'A005',
		AssetName: '마우스',
		UpdateDate: '2024-09-10',
		UpdateBy: '정미래',
		UpdateReason: '버튼 고장',
	},
	{
		UpdateNo: 6,
		AssetCode: 'A006',
		AssetName: '서버',
		UpdateDate: '2024-09-11',
		UpdateBy: '이철수',
		UpdateReason: '서버 리부팅',
	},
	{
		UpdateNo: 7,
		AssetCode: 'A007',
		AssetName: '라우터',
		UpdateDate: '2024-09-12',
		UpdateBy: '김지은',
		UpdateReason: '네트워크 설정 변경',
	},
	{
		UpdateNo: 8,
		AssetCode: 'A008',
		AssetName: '스위치',
		UpdateDate: '2024-09-13',
		UpdateBy: '윤주원',
		UpdateReason: '포트 추가',
	},
	{
		UpdateNo: 9,
		AssetCode: 'A009',
		AssetName: '프로젝터',
		UpdateDate: '2024-09-14',
		UpdateBy: '한가람',
		UpdateReason: '해상도 수정',
	},
	{
		UpdateNo: 10,
		AssetCode: 'A010',
		AssetName: '헤드셋',
		UpdateDate: '2024-09-15',
		UpdateBy: '오민석',
		UpdateReason: '사운드 문제 수정',
	},
	{
		UpdateNo: 11,
		AssetCode: 'A011',
		AssetName: '노트북',
		UpdateDate: '2024-09-16',
		UpdateBy: '서지혜',
		UpdateReason: '배터리 교체',
	},
	{
		UpdateNo: 12,
		AssetCode: 'A012',
		AssetName: '스피커',
		UpdateDate: '2024-09-17',
		UpdateBy: '이현수',
		UpdateReason: '소리 출력 불량',
	},
	{
		UpdateNo: 13,
		AssetCode: 'A013',
		AssetName: '캠코더',
		UpdateDate: '2024-09-18',
		UpdateBy: '김민정',
		UpdateReason: '녹화 파일 손상 문제',
	},
	{
		UpdateNo: 14,
		AssetCode: 'A014',
		AssetName: '테이블트',
		UpdateDate: '2024-09-19',
		UpdateBy: '최우진',
		UpdateReason: '터치 불량 수정',
	},
	{
		UpdateNo: 15,
		AssetCode: 'A015',
		AssetName: '전화기',
		UpdateDate: '2024-09-20',
		UpdateBy: '장미래',
		UpdateReason: '회선 연결 문제',
	},
	{
		UpdateNo: 16,
		AssetCode: 'A016',
		AssetName: '프린터',
		UpdateDate: '2024-09-21',
		UpdateBy: '박주현',
		UpdateReason: '잉크 교체',
	},
	{
		UpdateNo: 17,
		AssetCode: 'A017',
		AssetName: '모니터',
		UpdateDate: '2024-09-22',
		UpdateBy: '정수빈',
		UpdateReason: '전원 문제',
	},
	{
		UpdateNo: 18,
		AssetCode: 'A018',
		AssetName: '컴퓨터',
		UpdateDate: '2024-09-23',
		UpdateBy: '고영훈',
		UpdateReason: '프로세서 업그레이드',
	},
	{
		UpdateNo: 19,
		AssetCode: 'A019',
		AssetName: '라우터',
		UpdateDate: '2024-09-24',
		UpdateBy: '민상우',
		UpdateReason: '네트워크 속도 개선',
	},
	{
		UpdateNo: 20,
		AssetCode: 'A020',
		AssetName: '서버',
		UpdateDate: '2024-09-25',
		UpdateBy: '강수정',
		UpdateReason: '하드디스크 교체',
	},
];

const quickAccessFiles = [
	{
		icon: 'mdi mdi-file-pdf-box font-16',
		name: 'Docs PDF',
		size: '7.5 MB',
		location: '[태림]화면설계서_V4_240813.pdf',
	},
];

export { assetUpdates, quickAccessFiles };
