const demands = [
	{
		demandNo: 1,
		demandType: 'update',
		demandDate: '2024-09-06',
		demandBy: '이창현',
		demandStatus: 'UNCONFIRMED',
		subRows: [
			{
				demandNo: 1,
				demandType: 'update',
				demandDate: '2024-09-06',
				demandBy: '이창현',
				demandStatus: 'UNCONFIRMED',
			},
			{
				demandNo: 1,
				demandType: 'update',
				demandDate: '2024-09-06',
				demandBy: '이창현',
				demandStatus: 'UNCONFIRMED',
			},
			{
				demandNo: 1,
				demandType: 'update',
				demandDate: '2024-09-06',
				demandBy: '이창현',
				demandStatus: 'UNCONFIRMED',
			},
			{
				demandNo: 1,
				demandType: 'update',
				demandDate: '2024-09-06',
				demandBy: '이창현',
				demandStatus: 'UNCONFIRMED',
			},
		],
	},
	{
		demandNo: 2,
		demandType: 'delete',
		demandDate: '2024-09-07',
		demandBy: '김영희',
		demandStatus: 'Processing',
	},
	{
		demandNo: 3,
		demandType: 'AllUpdate',
		demandDate: '2024-09-08',
		demandBy: '박철수',
		demandStatus: 'APPROVE',
	},
	{
		demandNo: 4,
		demandType: 'AllDelete',
		demandDate: '2024-09-09',
		demandBy: '최민수',
		demandStatus: 'REFUSAL',
	},
	{
		demandNo: 5,
		demandType: 'update',
		demandDate: '2024-09-10',
		demandBy: '정미래',
		demandStatus: 'UNCONFIRMED',
	},
	{
		demandNo: 6,
		demandType: 'delete',
		demandDate: '2024-09-11',
		demandBy: '이철수',
		demandStatus: 'Processing',
	},
	{
		demandNo: 7,
		demandType: 'AllUpdate',
		demandDate: '2024-09-12',
		demandBy: '김지은',
		demandStatus: 'APPROVE',
	},
	{
		demandNo: 8,
		demandType: 'AllDelete',
		demandDate: '2024-09-13',
		demandBy: '윤주원',
		demandStatus: 'REFUSAL',
	},
	{
		demandNo: 9,
		demandType: 'update',
		demandDate: '2024-09-14',
		demandBy: '한가람',
		demandStatus: 'UNCONFIRMED',
	},
	{
		demandNo: 10,
		demandType: 'delete',
		demandDate: '2024-09-15',
		demandBy: '오민석',
		demandStatus: 'Processing',
	},
	{
		demandNo: 11,
		demandType: 'update',
		demandDate: '2024-09-16',
		demandBy: '서지혜',
		demandStatus: 'Processing',
	},
	{
		demandNo: 12,
		demandType: 'AllUpdate',
		demandDate: '2024-09-17',
		demandBy: '이현수',
		demandStatus: 'UNCONFIRMED',
	},
	{
		demandNo: 13,
		demandType: 'delete',
		demandDate: '2024-09-18',
		demandBy: '김민정',
		demandStatus: 'APPROVE',
	},
	{
		demandNo: 14,
		demandType: 'AllDelete',
		demandDate: '2024-09-19',
		demandBy: '최우진',
		demandStatus: 'Processing',
	},
	{
		demandNo: 15,
		demandType: 'update',
		demandDate: '2024-09-20',
		demandBy: '장미래',
		demandStatus: 'REFUSAL',
	},
	{
		demandNo: 16,
		demandType: 'delete',
		demandDate: '2024-09-21',
		demandBy: '박주현',
		demandStatus: 'UNCONFIRMED',
	},
	{
		demandNo: 17,
		demandType: 'AllUpdate',
		demandDate: '2024-09-22',
		demandBy: '정수빈',
		demandStatus: 'REFUSAL',
	},
	{
		demandNo: 18,
		demandType: 'update',
		demandDate: '2024-09-23',
		demandBy: '고영훈',
		demandStatus: 'APPROVE',
	},
	{
		demandNo: 19,
		demandType: 'AllDelete',
		demandDate: '2024-09-24',
		demandBy: '민상우',
		demandStatus: 'Processing',
	},
	{
		demandNo: 20,
		demandType: 'delete',
		demandDate: '2024-09-25',
		demandBy: '강수정',
		demandStatus: 'UNCONFIRMED',
	},
];

export { demands };
